const PRODUCTS = [
    // --- PROTECTORES SOLARES ---
    { id: 1, category: "Protectores Solares", name: "DERMABLOCK TONE UP SUN CREAM", price: 16.00, img: "./images/P-0037.Foto-Refencia.021618.jpg", description: "Protector solar facial SPF50+ PA++++ con efecto tone-up que unifica e ilumina el rostro; textura ligera y acabado natural.", ingredients: "Purified Water; Cyclopentasiloxane; Zinc Oxide; Homosalate; Ethylhexyl Salicylate; Titanium Dioxide; Niacinamide; (lista completa en ficha técnica)", source: "https://www.bing.com/search?q=DERMABLOCK+TONE+UP+SUN+CREAM" },
    { id: 2, category: "Protectores Solares", name: "DERMABLOCK AQUA SUN CREAM", price: 16.00, img: "./images/P-0038.Foto-Refencia.021719.jpg", description: "Protector solar de acabado hidratante y sensación ligera, pensado para uso diario y pieles que buscan confort sin residuo blanco.", ingredients: "Water; Ethylhexyl Methoxycinnamate; Ethylhexyl Salicylate; Butylene Glycol; C12-15 Alkyl Benzoate; Diethylaminohydroxybenzoyl Hexyl Benzoate; Homosalate; Octocrylene; Titanium Dioxide; 1,2-Hexanediol; Niacinamide; Caprylyl Methicone; Echium Plantagineum Seed Oil; Glyceryl Stearate; Tocopherol; Ascorbic Acid; Adenosine; (lista completa en ficha técnica)", source: "https://www.bing.com/search?q=DERMABLOCK+AQUA+SUN+CREAM" },
    { id: 3, category: "Protectores Solares", name: "DERMABLOCK VITAL SUN AMPOULE", price: 16.00, img: "./images/P-0039.Foto-Refencia.021930.jpg", description: "Ampolla/serum con protección y beneficios antioxidantes para brillo y protección diaria; formato concentrado para mejorar la piel.", ingredients: "Water, Dibutyl Adipate, Propanediol, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Polymethylsilsesquioxane, Ethylhexyl Triazone, Niacinamide, Methylene Bis-Benzotriazolyl Tetramethylbutylphenol.", source: "https://www.bing.com/search?q=DERMABLOCK+VITAL+SUN+AMPOULE" },
    { id: 4, category: "Protectores Solares", name: "ORIOX ALL DAY SUN CREAM", price: 16.00, img: "./images/P-0040.Foto-Refencia.022032.png", description: "Protector solar de uso diario diseñado para protección y confort todo el día; textura ligera y aplicable bajo maquillaje.", ingredients: "Water, Ethylhexyl Methoxycinnamate, Zinc Oxide, Mineral Oil, Glycerin, Ethylhexyl Salicylate, Titanium Dioxide, Isopropyl Myristate, Adenosine.", source: "https://www.bing.com/search?q=ORIOX+ALL+DAY+SUN+CREAM" },
    
    // --- LIMPIADORES Y SERUMS ---
    { id: 5, category: "Limpiadores y Serums", name: "Mixsoon Centella Asiatica Toner 300ml", price: 35.00, img: "./images/P-0003.Foto-Refencia.165441.jpg", description: "Tónico calmante con extracto de Centella Asiática para reducir enrojecimiento e hidratar la piel después de la limpieza.", ingredients: "100% Centella Asiatica Extract.", source: "https://www.bing.com/search?q=Mixsoon+Centella+Asiatica+Toner+300ml" },
    { id: 6, category: "Limpiadores y Serums", name: "Mixsoon Glacier Water Hyaluronic Acid Serum 100ml", price: 40.00, img: "./images/P-0005.Foto-Refencia.165925.jpg", description: "Sérum con ácido hialurónico para hidratación intensa y relleno de la piel; apto como paso de hidratación profunda.", ingredients: "Glacier Water, Butylene Glycol, 1,2-Hexanediol, Sodium Hyaluronate.", source: "https://www.bing.com/search?q=Mixsoon+Glacier+Water+Hyaluronic+Acid+Serum+100ml" },
    { id: 7, category: "Limpiadores y Serums", name: "Orjena Real Deep Cleansing Oil 150ml", price: 35.00, img: "./images/P-0008.Foto-Refencia.171447.jpg", description: "Aceite limpiador que emulsiona con agua para retirar maquillaje y SPF sin resecar; indicado para doble limpieza coreana.", ingredients: "Mineral Oil, Isopropyl Myristate, PEG-20 Glyceryl Triisostearate, Vitis Vinifera (Grape) Seed Oil, Simmondsia Chinensis (Jojoba) Seed Oil.", source: "https://www.bing.com/search?q=Orjena+Real+Deep+Cleansing+Oil+150ml" },
    { id: 8, category: "Limpiadores y Serums", name: "Garlic AC Reedle Shot Cream 50ml", price: 30.00, img: "./images/P-0031.Foto-Refencia.192554.jpg", description: "Crema con enfoque en control de acné y calmado de la piel; formulada para reducir brotes y equilibrar la piel grasa.", ingredients: "Water, Glycerin, Niacinamide, Silica (Reedle), Allium Sativum (Garlic) Bulb Extract, Centella Asiatica Extract.", source: "https://www.bing.com/search?q=Garlic+AC+Reedle+Shot+Cream+50ml" },
    { id: 9, category: "Limpiadores y Serums", name: "WELCOS ACNE CLEANSING FOAM", price: 18.00, img: "./images/P-0050.Foto-Refencia.023944.jpg", description: "Espuma limpiadora para piel propensa al acné; elimina impurezas y exceso de grasa sin desbalancear la barrera cutánea.", ingredients: "Water, Stearic Acid, Glycerin, Myristic Acid, Salicylic Acid (BHA), Potassium Hydroxide, Lauric Acid, Tea Tree Oil.", source: "https://www.bing.com/search?q=Welcos+Acne+Cleansing+Foam" },
    { id: 10, category: "Limpiadores y Serums", name: "WELCOS EGG CLEANSING FOAM", price: 18.00, img: "./images/P-0051.Foto-Refencia.024048.jpg", description: "Espuma limpiadora enriquecida con extracto de huevo para suavizar y mejorar la textura de la piel tras la limpieza.", ingredients: "Water, Stearic Acid, Myristic Acid, Potassium Hydroxide, Lauric Acid, Egg Yolk Extract, Albumen Extract.", source: "https://www.bing.com/search?q=Welcos+Egg+Cleansing+Foam" },
    { id: 11, category: "Limpiadores y Serums", name: "WELCOS ALOE CLEANSING FOAM", price: 18.00, img: "./images/P-0052.Foto-Refencia.024152.png", description: "Limpiador facial suave con extracto de Aloe Vera que calma y refresca la piel mientras elimina impurezas.", ingredients: "Water, Glycerin, Stearic Acid, Aloe Barbadensis Leaf Extract, Myristic Acid, Potassium Hydroxide, Lauric Acid.", source: "https://www.bing.com/search?q=WELCOS+ALOE+CLEANSING+FOAM" },
    { id: 12, category: "Limpiadores y Serums", name: "WELCOS MINT CLEANSING FOAM", price: 18.00, img: "./images/P-0053.Foto-Refencia.024305.jpg", description: "Espuma limpiadora con extracto de menta que proporciona una sensación de frescura intensa y control de grasa.", ingredients: "Water, Myristic Acid, Stearic Acid, Mentha Piperita (Peppermint) Leaf Extract, Menthol, Glycerin, Potassium Hydroxide.", source: "https://www.bing.com/search?q=WELCOS+MINT+CLEANSING+FOAM" },
    { id: 13, category: "Limpiadores y Serums", name: "DEEP! FOAMING CLEANSER", price: 20.00, img: "./images/P-0054.Foto-Refencia.024501.jpg", description: "Limpiador profundo que genera una espuma densa para penetrar en los poros y eliminar residuos de maquillaje.", ingredients: "Water, Glycerin, Potassium Cocoyl Glycinate, Sodium Lauroyl Glutamate, Lauryl Betaine, 1,2-Hexanediol.", source: "https://www.bing.com/search?q=DEEP!+FOAMING+CLEANSER" },

    // --- MASCARILLAS ---
    { id: 14, category: "Mascarillas", name: "Mixsoon Bean Collagen Hydrogel Mask", price: 10.00, img: "./images/P-0028.Foto-Refencia.165923.jpg", description: "Mascarilla de hidrogel ultra-adherente formulada con colágeno derivado de frijol para mejorar la elasticidad.", ingredients: "Water, Glycerin, Bean Ferment Extract, Hydrolyzed Collagen, Niacinamide, Ceramide NP.", source: "https://www.bing.com/search?q=Mixsoon+Bean+Collagen+Hydrogel+Mask" },
    { id: 15, category: "Mascarillas", name: "Mixsoon Soybean Milk Pad", price: 8.00, img: "./images/P-0007.Foto-Refencia.170933.jpg", description: "Pads de algodón empapados en esencia de leche de soja para una nutrición instantánea y suavidad en la piel.", ingredients: "Soy Milk Extract, Lactobacillus/Soybean Ferment Extract, Glycerin, Panthenol.", source: "https://www.bing.com/search?q=Mixsoon+Soybean+Milk+Pad" },
    { id: 16, category: "Mascarillas", name: "Sadoer Collagen Moisturizing Sakura Tender Mask", price: 5.00, img: "./images/P-0011.Foto-Refencia.184917.jpg", description: "Mascarilla hidratante con colágeno y extracto de flor de cerezo (Sakura) para una piel luminosa y suave.", ingredients: "Water, Propylene Glycol, Collagen, Prunus Lannesiana Flower Extract, Hyaluronic Acid.", source: "https://www.bing.com/search?q=Sadoer+Collagen+Sakura+Mask" },
    { id: 17, category: "Mascarillas", name: "Compressed Mask", price: 3.00, img: "./images/P-0013.Foto-Refencia.185510.jpg", description: "Mascarillas de algodón comprimido listas para ser activadas con tu tónico o esencia favorita.", ingredients: "100% Natural Cotton / Rayon.", source: "https://www.bing.com/search?q=Compressed+Cotton+Mask+Diy" },
    { id: 18, category: "Mascarillas", name: "Kleam HYDRATION BOOST Premiun mask", price: 10.00, img: "./images/P-0027.Foto-Refencia.045530.png", description: "Mascarilla premium de alta concentración para recuperar pieles deshidratadas y opacas en minutos.", ingredients: "Aqua, Hyaluronic Acid, Sodium PCA, Glycerin, Allantoin, Aloe Barbadensis Extract.", source: "https://www.bing.com/search?q=Kleam+HYDRATION+BOOST+mask" },
    { id: 19, category: "Mascarillas", name: "Luminous Skinpack VT COSMETICS", price: 20.00, img: "./images/P-0032.Foto-Refencia.171645.jpg", description: "Pack de mascarillas iluminadoras que ayudan a revitalizar el tono de la piel y dar un brillo saludable.", ingredients: "Water, Niacinamide, Glutathione, Pearl Extract, Butylene Glycol, 1,2-Hexanediol.", source: "https://www.bing.com/search?q=Luminous+Skinpack+VT+COSMETICS" },
    { id: 20, category: "Mascarillas", name: "VASELINE MOISTURIZING (HIDRATANTE)", price: 8.00, img: "./images/P-0010.Foto-Refencia.184528.jpg", description: "Mascarilla de hoja con esencia de vaselina para sellar la humedad en la piel extremadamente seca.", ingredients: "Water, Glycerin, Petrolatum, Ceramide NP, Panthenol, Tocopheryl Acetate.", source: "https://www.bing.com/search?q=VASELINE+MOISTURIZING+mask" },
    { id: 21, category: "Mascarillas", name: "VASELINE HYDRATING (HIDRATACIÓN)", price: 8.00, img: "./images/P-0033.Foto-Refencia.020921.jpg", description: "Mascarilla diseñada para reponer los niveles de agua en la piel con la suavidad clásica de la vaselina.", ingredients: "Water, Sodium Hyaluronate, Petrolatum, Glycerin, Xanthan Gum.", source: "https://www.bing.com/search?q=VASELINE+HYDRATING+mask" },
    { id: 22, category: "Mascarillas", name: "VASELINE NOURISHING (NUTRITIVA)", price: 8.00, img: "./images/P-0034.Foto-Refencia.021044.jpg", description: "Mascarilla nutritiva profunda que ayuda a fortalecer la barrera cutánea con lípidos esenciales.", ingredients: "Water, Glycerin, Petrolatum, Butyrospermum Parkii (Shea) Butter, Niacinamide.", source: "https://www.bing.com/search?q=VASELINE+NOURISHING+mask" },
    { id: 23, category: "Mascarillas", name: "VASELINE SOOTHING (CALMANTE)", price: 8.00, img: "./images/P-0035.Foto-Refencia.021248.png", description: "Mascarilla calmante ideal para pieles irritadas o expuestas al sol; refresca y suaviza al instante.", ingredients: "Water, Aloe Barbadensis Leaf Extract, Petrolatum, Centella Asiatica Extract.", source: "https://www.bing.com/search?q=VASELINE+SOOTHING+mask" },
    { id: 24, category: "Mascarillas", name: "CICA CALMING 3 STEP MASK PACK VT COSMETICS", price: 10.00, img: "./images/P-0041.Foto-Refencia.022414.jpg", description: "Tratamiento completo de 3 pasos (limpiador, esencia y mascarilla) con Centella Asiática para calmar pieles sensibles.", ingredients: "Centella Asiatica Extract, Madecassoside, Asiaticoside, Propolis Extract, Hyaluronic Acid.", source: "https://www.bing.com/search?q=CICA+CALMING+3+STEP+MASK+VT" },
    { id: 25, category: "Mascarillas", name: "REEDLE SHOT GLUTATHIONE ESSENCE PADS", price: 15.00, img: "./images/P-0042.Foto-Refencia.022559.jpg", description: "Pads con tecnología Reedle Shot y Glutatión para exfoliar suavemente y potenciar la luminosidad.", ingredients: "Silica (Reedle), Glutathione, Niacinamide, Vitamin C, Butylene Glycol.", source: "https://www.bing.com/search?q=REEDLE+SHOT+GLUTATHIONE+ESSENCE+PADS" },
    { id: 26, category: "Mascarillas", name: "REEDLE SHOT ARGIRELINE PEPTIDE ESSENCE PADS", price: 15.00, img: "./images/P-0043.Foto-Refencia.022733.jpg", description: "Pads con péptidos de Argireline (efecto botox-like) para mejorar la apariencia de líneas de expresión.", ingredients: "Silica, Acetyl Hexapeptide-8 (Argireline), Adenosine, Glycerin.", source: "https://www.bing.com/search?q=REEDLE+SHOT+ARGIRELINE+PEPTIDE+ESSENCE+PADS" },
    { id: 27, category: "Mascarillas", name: "REEDLE SHOT EGF ESSENCE PADS", price: 15.00, img: "./images/P-0044.Foto-Refencia.022848.jpg", description: "Pads regeneradores con Factor de Crecimiento Epidérmico (EGF) para reparar y fortalecer la dermis.", ingredients: "Silica, sh-Oligopeptide-1 (EGF), Allantoin, Panthenol, Centella Extract.", source: "https://www.bing.com/search?q=REEDLE+SHOT+EGF+ESSENCE+PADS" },
    { id: 28, category: "Mascarillas", name: "MEDIHEAL CERAMIDE MASK", price: 8.00, img: "./images/P-0045.Foto-Refencia.023128.jpg", description: "Mascarilla de barrera que utiliza ceramidas para proteger la piel y evitar la pérdida de humedad.", ingredients: "Water, Glycerin, Ceramide NP, Phytosphingosine, Cholesterol, Lecithin.", source: "https://www.bing.com/search?q=MEDIHEAL+CERAMIDE+MASK" },
    { id: 29, category: "Mascarillas", name: "MEDIHEAL COLLAGEN MASK", price: 8.00, img: "./images/P-0046.Foto-Refencia.023235.jpg", description: "Mascarilla reafirmante con colágeno marino para devolver elasticidad y turgencia al rostro.", ingredients: "Hydrolyzed Collagen, Elastin, Vitamin E, Glycerin, Sodium Hyaluronate.", source: "https://www.bing.com/search?q=MEDIHEAL+COLLAGEN+MASK" },
    { id: 30, category: "Mascarillas", name: "MEDIHEAL VITAMIN C MASK", price: 8.00, img: "./images/P-0047.Foto-Refencia.023430.jpg", description: "Mascarilla iluminadora rica en Vitamina C para combatir manchas y fatiga cutánea.", ingredients: "Sodium Ascorbyl Phosphate, White Willow Bark Extract, Niacinamide, Glycerin.", source: "https://www.bing.com/search?q=MEDIHEAL+VITAMIN+C+MASK" },
    { id: 31, category: "Mascarillas", name: "MEDIHEAL TEATREE MASK", price: 8.00, img: "./images/P-0048.Foto-Refencia.023550.jpg", description: "Mascarilla purificante líder en ventas con extracto de árbol de té; ideal para controlar grasa y brotes.", ingredients: "Melaleuca Alternifolia (Tea Tree) Extract, Centella Asiatica, Pine Leaf Extract.", source: "https://www.bing.com/search?q=MEDIHEAL+TEATREE+MASK" },
    { id: 32, category: "Mascarillas", name: "MEDIHEAL HYALURONATE MASK", price: 8.00, img: "./images/P-0049.Foto-Refencia.023711.jpg", description: "Bomba de hidratación con múltiples tipos de ácido hialurónico para un efecto de piel jugosa.", ingredients: "Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Potassium Hyaluronate, Aquaxyl.", source: "https://www.bing.com/search?q=MEDIHEAL+HYALURONATE+MASK" },
    { id: 33, category: "Mascarillas", name: "POMEGRANATE MASK", price: 5.00, img: "./images/P-0055.Foto-Refencia.031548.png", description: "Mascarilla antioxidante de Granada que aporta vitalidad y previene el envejecimiento prematuro.", ingredients: "Water, Punica Granatum Fruit Extract, Glycerin, Butylene Glycol.", source: "https://www.bing.com/search?q=POMEGRANATE+SKIN+MASK+ingredients" },
    { id: 34, category: "Mascarillas", name: "GREEN TEA MASK", price: 5.00, img: "./images/P-0056.Foto-Refencia.031634.png", description: "Mascarilla de Té Verde con propiedades antiinflamatorias y refrescantes para pieles mixtas.", ingredients: "Water, Camellia Sinensis Leaf Extract, Allantoin, Glycerin.", source: "https://www.bing.com/search?q=GREEN+TEA+SKIN+MASK+ingredients" },
    { id: 35, category: "Mascarillas", name: "ALOE MASK", price: 5.00, img: "./images/P-0057.Foto-Refencia.031730.png", description: "Mascarilla básica de Aloe Vera para hidratar y calmar cualquier tipo de piel después de un día largo.", ingredients: "Water, Aloe Barbadensis Leaf Extract, Dipropylene Glycol, Panthenol.", source: "https://www.bing.com/search?q=ALOE+VERA+SKIN+MASK+ingredients" },
    { id: 36, category: "Mascarillas", name: "SNAKE MASK", price: 5.00, img: "./images/P-0058.Foto-Refencia.031820.png", description: "Mascarilla con péptido Syn-Ake (veneno de serpiente sintético) para tensar y reafirmar la piel.", ingredients: "Water, Dipeptide Diaminobutyroyl Benzylamide Diacetate, Glycerin, Adenosine.", source: "https://www.bing.com/search?q=SNAKE+VENOM+PEPTIDE+MASK" },
    { id: 37, category: "Mascarillas", name: "POTATO MASK", price: 5.00, img: "./images/P-0059.Foto-Refencia.031900.png", description: "Mascarilla de extracto de Patata que ayuda a desinflamar y calmar pieles fatigadas por el sol.", ingredients: "Water, Solanum Tuberosum (Potato) Pulp Extract, Glycerin, Sodium Hyaluronate.", source: "https://www.bing.com/search?q=POTATO+SKIN+MASK+korea" },

    // --- PARCHES PARA ACNÉ ---
    { id: 38, category: "Parches para Acné", name: "RED SPOT SPOT CARE PATCH (PARCHES ACNE)", price: 4.00, img: "./images/P-0060.Foto-Refencia.032046.png", description: "Parches hidrocoloides ultrafinos para proteger granitos rojos de bacterias y acelerar su curación.", ingredients: "Hydrocolloid, Tea Tree Oil, Salicylic Acid.", source: "https://www.bing.com/search?q=RED+SPOT+CARE+PATCH" },
    { id: 39, category: "Parches para Acné", name: "YELLOW SPOT SPOT CARE PATCH (PARCHES ACNE)", price: 4.00, img: "./images/P-0061.Foto-Refencia.032139.png", description: "Parches para granitos con pus (punto amarillo); absorben impurezas y fluidos de forma higiénica.", ingredients: "Hydrocolloid Sheet.", source: "https://www.bing.com/search?q=YELLOW+SPOT+CARE+PATCH" },
    { id: 40, category: "Parches para Acné", name: "WITHDERM SKINCOVER (PARCHES ACNE)", price: 5.00, img: "./images/P-0062.Foto-Refencia.032252.png", description: "Parches transparentes para cubrir imperfecciones mientras se aplica maquillaje, protegiendo la zona.", ingredients: "Polyurethane Film, Hydrocolloid.", source: "https://www.bing.com/search?q=WITHDERM+SKINCOVER+patch" },
    { id: 41, category: "Parches para Acné", name: "Garlic AC Reedle Shot Spot Patch", price: 14.00, img: "./images/P-0063.Foto-Refencia.001016.jpg", description: "Parches avanzados con micro-agujas (Reedle) para entregar ingredientes directamente al foco del acné.", ingredients: "Silica, Allium Sativum (Garlic) Extract, Madecassoside, Salicylic Acid.", source: "https://www.bing.com/search?q=Garlic+AC+Reedle+Shot+Spot+Patch" },
    { id: 42, category: "Parches para Acné", name: "Garlic AC Reedle Shot Point Patch", price: 14.00, img: "./images/P-0064.Foto-Refencia.001058.jpg", description: "Versión puntual de los parches Reedle Shot, diseñados para tratar granitos internos o dolorosos.", ingredients: "Silica, Sodium Hyaluronate, Garlic Extract, Niacinamide.", source: "https://www.bing.com/search?q=Garlic+AC+Reedle+Shot+Point+Patch" },
    { id: 43, category: "Parches para Acné", name: "Acne Patch (40 Parches)", price: 4.00, img: "./images/P-0012.Foto-Refencia.185250.jpg", description: "Set de 40 parches de diferentes tamaños para cubrir brotes de acné y evitar cicatrices.", ingredients: "Hydrocolloid.", source: "https://www.bing.com/search?q=generic+acne+patch+40+pcs" },
    { id: 44, category: "Parches para Acné", name: "Blackhead Nose Patch (Und)", price: 3.00, img: "./images/P-0014.Foto-Refencia.185942.jpg", description: "Tira para la nariz que extrae puntos negros y exceso de sebo en un solo uso.", ingredients: "PVP, Water, Charcoal Powder, Hamamelis Virginiana Extract.", source: "https://www.bing.com/search?q=Blackhead+Nose+Patch+ingredients" },

    // --- MERCH KPOP ---
    { id: 45, category: "Merch Kpop", name: "BTS TINYTAN Jungkook", price: 10.00, img: "./images/P-0015.Foto-Refencia.190823.png", description: "Figura o accesorio coleccionable del personaje TinyTan basado en Jungkook de BTS.", ingredients: "PVC / Vinyl (Material)", source: "" },
    { id: 46, category: "Merch Kpop", name: "BTS TINYTAN Jimin", price: 10.00, img: "./images/P-0016.Foto-Refencia.190903.png", description: "Figura o accesorio coleccionable del personaje TinyTan basado en Jimin de BTS.", ingredients: "PVC / Vinyl (Material)", source: "" },
    { id: 47, category: "Merch Kpop", name: "BTS TINYTAN Jin", price: 10.00, img: "./images/P-0017.Foto-Refencia.190937.png", description: "Figura o accesorio coleccionable del personaje TinyTan basado en Jin de BTS.", ingredients: "PVC / Vinyl (Material)", source: "" },
    { id: 48, category: "Merch Kpop", name: "BTS TINYTAN RM", price: 10.00, img: "./images/P-0018.Foto-Refencia.191013.png", description: "Figura o accesorio coleccionable del personaje TinyTan basado en RM de BTS.", ingredients: "PVC / Vinyl (Material)", source: "" },
    { id: 49, category: "Merch Kpop", name: "BTS TINYTAN J-Hope", price: 10.00, img: "./images/P-0019.Foto-Refencia.191045.png", description: "Figura o accesorio coleccionable del personaje TinyTan basado en J-Hope de BTS.", ingredients: "PVC / Vinyl (Material)", source: "" },

    // --- VARIADOS ---
    { id: 50, category: "Variados", name: "Rutina de Lujo Mixsoon 🎄✨", price: 95.00, img: "./images/COMBO1.jpg", description: "Este set es el regalo perfecto para quienes aman cuidarse con lo mejor. Productos coreanos de alta gama para una piel radiante esta Navidad.", ingredients: "", source: "" },
    { id: 51, category: "Variados", name: "Protección y Brillo Diario ☀️", price: 50.00, img: "./images/COMBO2.jpg", description: "No dejes que el sol de estas fiestas apague tu glow. ✨️🙌🙂‍ Este combo esencial te mantiene protegida e impecable. ¡Un básico indispensable para tu día a día!", ingredients: "", source: "" },
    { id: 52, category: "Variados", name: "Mascarillas & Relax Navideño 🌟", price: 30.00, img: "./images/COMBO3.jpg", description: "¿Noche de spa en casa? ¡Sí, por favor! Este combo trae 4 mascarillas y parches para consentirte.¡El auto-regalo perfecto o para tu amiga secreta!", ingredients: "", source: "" },
    { id: 53, category: "Variados", name: "Anti-Acné & Purificación 🌿", price: 56.00, img: "./images/COMBO4.jpg", description: "No dejes que las imperfecciones arruinen tus celebraciones. Este combo es tu aliado para una piel clara y pura esta Navidad.¡Piel impecable, fiestas felices!", ingredients: "", source: "" },
    { id: 54, category: "Variados", name: "Iluminación y Prepárate para la Fiesta ✨", price: 52.00, img: "./images/COMBO5.jpg", description: "¡Consigue un glow espectacular para todas tus celebraciones! Este combo ilumina y protege tu piel, dejándola lista para deslumbrar.¡Sé la estrella de la noche!", ingredients: "", source: "" },
];